const CHANNELS = ['WHATSAPP', 'TELEGRAM', 'INSTAGRAM', 'EMAIL', 'WEB_FORM', 'SMS'];

const LEAD_STATUSES = [
  'NEW',
  'CONTACTED',
  'QUALIFIED',
  'CONSULTATION',
  'CONVERTED',
  'CLOSED',
];

const USER_ROLES = ['CONSULTANT', 'ADMIN', 'MANAGER'];

const MESSAGE_DIRECTIONS = ['IN', 'OUT'];
const MESSAGE_STATUSES = ['RECEIVED', 'SENT', 'READ', 'FAILED'];

module.exports = {
  CHANNELS,
  LEAD_STATUSES,
  USER_ROLES,
  MESSAGE_DIRECTIONS,
  MESSAGE_STATUSES,
};
